# Generated by Django 5.2.7 on 2026-03-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloglike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bloglike',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='bloglike',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='BlogLike',
        ),
    ]
