# Generated by Django 5.2.7 on 2026-07-19 10:43

import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='uhid',
            field=models.CharField(default=patient.models.generate_uhid, editable=False, max_length=20, unique=True),
        ),
    ]
