# Generated by Django 5.2.7 on 2025-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('GOVT', 'Government'), ('PRIVATE', 'Private')], db_index=True, default='PRIVATE', max_length=10),
        ),
    ]
